<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Student;

class StudentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'nim' => '1234567890',
                'name' => 'Ahmad Fauzi',
                'faculty' => 'Fakultas Teknik',
                'department' => 'Teknik Informatika',
                'cohort_year' => 2022,
                'current_semester' => 5,
                'status' => 'active',
                'phone' => '081234567890',
                'email' => 'ahmad.fauzi@student.telkomuniversity.ac.id',
                'address' => 'Jl. Telekomunikasi No. 1, Bandung',
                'father_name' => 'Budi Santoso',
                'mother_name' => 'Sari Dewi',
                'academic_year' => '2022/2023',
                'outstanding_amount' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '1234567891',
                'name' => 'Siti Nurhaliza',
                'faculty' => 'Fakultas Ekonomi',
                'department' => 'Manajemen',
                'cohort_year' => 2021,
                'current_semester' => 7,
                'status' => 'active',
                'phone' => '081234567891',
                'email' => 'siti.nurhaliza@student.telkomuniversity.ac.id',
                'address' => 'Jl. Buah Batu No. 25, Bandung',
                'father_name' => 'Dedi Kurniawan',
                'mother_name' => 'Rina Sari',
                'academic_year' => '2021/2022',
                'outstanding_amount' => 2500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '1234567892',
                'name' => 'Budi Hartono',
                'faculty' => 'Fakultas Ilmu Komputer',
                'department' => 'Sistem Informasi',
                'cohort_year' => 2023,
                'current_semester' => 3,
                'status' => 'active',
                'phone' => '081234567892',
                'email' => 'budi.hartono@student.telkomuniversity.ac.id',
                'address' => 'Jl. Dago No. 10, Bandung',
                'father_name' => 'Joko Widodo',
                'mother_name' => 'Sari Indah',
                'academic_year' => '2023/2024',
                'outstanding_amount' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '1234567893',
                'name' => 'Dewi Sartika',
                'faculty' => 'Fakultas Komunikasi',
                'department' => 'Ilmu Komunikasi',
                'cohort_year' => 2020,
                'current_semester' => 8,
                'status' => 'graduated',
                'phone' => '081234567893',
                'email' => 'dewi.sartika@student.telkomuniversity.ac.id',
                'address' => 'Jl. Cihampelas No. 15, Bandung',
                'father_name' => 'Hasan Basri',
                'mother_name' => 'Lina Marlina',
                'academic_year' => '2020/2021',
                'outstanding_amount' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '1234567894',
                'name' => 'Reza Pratama',
                'faculty' => 'Fakultas Teknik',
                'department' => 'Teknik Elektro',
                'cohort_year' => 2022,
                'current_semester' => 5,
                'status' => 'inactive',
                'phone' => '081234567894',
                'email' => 'reza.pratama@student.telkomuniversity.ac.id',
                'address' => 'Jl. Setiabudi No. 30, Bandung',
                'father_name' => 'Agus Salim',
                'mother_name' => 'Ratih Kumala',
                'academic_year' => '2022/2023',
                'outstanding_amount' => 5000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '1234567895',
                'name' => 'Maya Sari',
                'faculty' => 'Fakultas Sains',
                'department' => 'Matematika',
                'cohort_year' => 2021,
                'current_semester' => 6,
                'status' => 'active',
                'phone' => '081234567895',
                'email' => 'maya.sari@student.telkomuniversity.ac.id',
                'address' => 'Jl. Sukajadi No. 45, Bandung',
                'father_name' => 'Bambang Hermawan',
                'mother_name' => 'Fitri Handayani',
                'academic_year' => '2021/2022',
                'outstanding_amount' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '1234567896',
                'name' => 'Andi Wijaya',
                'faculty' => 'Fakultas Hukum',
                'department' => 'Ilmu Hukum',
                'cohort_year' => 2019,
                'current_semester' => 8,
                'status' => 'dropped_out',
                'phone' => '081234567896',
                'email' => 'andi.wijaya@student.telkomuniversity.ac.id',
                'address' => 'Jl. Pasteur No. 50, Bandung',
                'father_name' => 'Sutrisno',
                'mother_name' => 'Endang Sulistyowati',
                'academic_year' => '2019/2020',
                'outstanding_amount' => 7500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '1234567897',
                'name' => 'Fatimah Zahra',
                'faculty' => 'Fakultas Teknik',
                'department' => 'Teknik Industri',
                'cohort_year' => 2023,
                'current_semester' => 2,
                'status' => 'active',
                'phone' => '081234567897',
                'email' => 'fatimah.zahra@student.telkomuniversity.ac.id',
                'address' => 'Jl. Dipatiukur No. 20, Bandung',
                'father_name' => 'Abdul Rahman',
                'mother_name' => 'Khadijah',
                'academic_year' => '2023/2024',
                'outstanding_amount' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '1234567898',
                'name' => 'Rizki Ramadhan',
                'faculty' => 'Fakultas Ilmu Komputer',
                'department' => 'Teknik Informatika',
                'cohort_year' => 2024,
                'current_semester' => 1,
                'status' => 'active',
                'phone' => '081234567898',
                'email' => 'rizki.ramadhan@student.telkomuniversity.ac.id',
                'address' => 'Jl. Ciumbuleuit No. 35, Bandung',
                'father_name' => 'Ramadhan Pohan',
                'mother_name' => 'Siti Aisyah',
                'academic_year' => '2024/2025',
                'outstanding_amount' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '1234567899',
                'name' => 'Indah Permata',
                'faculty' => 'Fakultas Ekonomi',
                'department' => 'Akuntansi',
                'cohort_year' => 2020,
                'current_semester' => 8,
                'status' => 'graduated',
                'phone' => '081234567899',
                'email' => 'indah.permata@student.telkomuniversity.ac.id',
                'address' => 'Jl. Riau No. 12, Bandung',
                'father_name' => 'Permadi',
                'mother_name' => 'Indira Sari',
                'academic_year' => '2020/2021',
                'outstanding_amount' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($students as $student) {
            Student::create($student);
        }
    }
}
