version: '3.8'

services:
  # Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: stefia-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - database
      - redis
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=database
      - DB_DATABASE=stefia
      - DB_USERNAME=stefia
      - DB_PASSWORD=stefia123
      - REDIS_HOST=redis
    networks:
      - stefia-network

  # Web Server
  webserver:
    image: nginx:alpine
    container_name: stefia-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - stefia-network

  # Database
  database:
    image: mysql:8.0
    container_name: stefia-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stefia
      MYSQL_USER: stefia
      MYSQL_PASSWORD: stefia123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - stefia-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: stefia-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - stefia-network

  # Queue Worker
  queue:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: stefia-queue
    restart: unless-stopped
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
      - redis
    environment:
      - APP_ENV=production
      - DB_HOST=database
      - REDIS_HOST=redis
    networks:
      - stefia-network

  # Scheduler
  scheduler:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: stefia-scheduler
    restart: unless-stopped
    command: php artisan schedule:run
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
      - redis
    environment:
      - APP_ENV=production
      - DB_HOST=database
      - REDIS_HOST=redis
    networks:
      - stefia-network

volumes:
  db_data:
    driver: local

networks:
  stefia-network:
    driver: bridge
